name: GoSungrow
version: 3.0.28
slug: gosungrow
url: https://github.com/roth-andreas/gosungrow-home-assistant
image: ghcr.io/roth-andreas/gosungrow-addon-{arch}
description: Publish Sungrow iSolarCloud data to Home Assistant over MQTT discovery.
panel_icon: mdi:solar-power
startup: services
boot: auto
init: false
homeassistant_api: true
services:
  - mqtt:want
map:
  - type: homeassistant_config
    path: /homeassistant
    read_only: false
arch:
  - aarch64
  - amd64
options:
  gosungrow_user: null
  gosungrow_password: null
  install_dashboard: true
  dashboard_language: auto
  debug: false
schema:
  gosungrow_user: str
  gosungrow_password: password
  install_dashboard: bool
  dashboard_language: str
  debug: bool
